insert into tb_pais (codigo, nome, sigla) values (1, 'Brasil', 'BR'); 
insert into tb_pais (codigo, nome, sigla) values (2, 'Afeganistão', 'AF'); 
insert into tb_pais (codigo, nome, sigla) values (3, 'Albânia, Republica da', 'AL'); 
insert into tb_pais (codigo, nome, sigla) values (4, 'Argélia', 'DZ'); 
insert into tb_pais (codigo, nome, sigla) values (5, 'Samoa Americana', 'AS'); 
insert into tb_pais (codigo, nome, sigla) values (6, 'Andorra', 'AD'); 
insert into tb_pais (codigo, nome, sigla) values (7, 'Angola', 'AO'); 
insert into tb_pais (codigo, nome, sigla) values (8, 'Anguilla', 'AI'); 
insert into tb_pais (codigo, nome, sigla) values (9, 'Antártida', 'AQ'); 
insert into tb_pais (codigo, nome, sigla) values (10, 'Antigua e Barbuda', 'AG'); 
insert into tb_pais (codigo, nome, sigla) values (11, 'Argentina', 'AR'); 
insert into tb_pais (codigo, nome, sigla) values (12, 'Armênia, Republica da', 'AM'); 
insert into tb_pais (codigo, nome, sigla) values (13, 'Aruba', 'AW'); 
insert into tb_pais (codigo, nome, sigla) values (14, 'Austrália', 'AU'); 
insert into tb_pais (codigo, nome, sigla) values (15, 'Áustria', 'AT'); 
insert into tb_pais (codigo, nome, sigla) values (16, 'Azerbaijão, Republica do', 'AZ'); 
insert into tb_pais (codigo, nome, sigla) values (17, 'Bahamas, Ilhas', 'BS'); 
insert into tb_pais (codigo, nome, sigla) values (18, 'Bahrein, Ilhas', 'BH'); 
insert into tb_pais (codigo, nome, sigla) values (19, 'Bangladesh', 'BD'); 
insert into tb_pais (codigo, nome, sigla) values (20, 'Barbados', 'BB'); 
insert into tb_pais (codigo, nome, sigla) values (21, 'Belarus, Republica da', 'BY'); 
insert into tb_pais (codigo, nome, sigla) values (22, 'Bélgica', 'BE'); 
insert into tb_pais (codigo, nome, sigla) values (23, 'Belize', 'BZ'); 
insert into tb_pais (codigo, nome, sigla) values (24, 'Benin', 'BJ'); 
insert into tb_pais (codigo, nome, sigla) values (25, 'Bermudas', 'BM'); 
insert into tb_pais (codigo, nome, sigla) values (26, 'Butão', 'BT'); 
insert into tb_pais (codigo, nome, sigla) values (27, 'Bolívia', 'BO'); 
insert into tb_pais (codigo, nome, sigla) values (28, 'Bósnia-herzegovina (Republica da)', 'BA'); 
insert into tb_pais (codigo, nome, sigla) values (29, 'Botsuana', 'BW'); 
insert into tb_pais (codigo, nome, sigla) values (30, 'Bouvet, Ilha', 'BV'); 
insert into tb_pais (codigo, nome, sigla) values (31, 'Território Britânico do Oceano Indico', 'IO'); 
insert into tb_pais (codigo, nome, sigla) values (32, 'Brunei', 'BN'); 
insert into tb_pais (codigo, nome, sigla) values (33, 'Bulgária, Republica da', 'BG'); 
insert into tb_pais (codigo, nome, sigla) values (34, 'Burkina Faso', 'BF'); 
insert into tb_pais (codigo, nome, sigla) values (35, 'Burundi', 'BI'); 
insert into tb_pais (codigo, nome, sigla) values (36, 'Camboja', 'KH'); 
insert into tb_pais (codigo, nome, sigla) values (37, 'Camarões', 'CM'); 
insert into tb_pais (codigo, nome, sigla) values (38, 'Canada', 'CA'); 
insert into tb_pais (codigo, nome, sigla) values (39, 'Cabo Verde, Republica de', 'CV'); 
insert into tb_pais (codigo, nome, sigla) values (40, 'Cayman, Ilhas', 'KY'); 
insert into tb_pais (codigo, nome, sigla) values (41, 'Republica Centro-Africana', 'CF'); 
insert into tb_pais (codigo, nome, sigla) values (42, 'Chade', 'TD'); 
insert into tb_pais (codigo, nome, sigla) values (43, 'Chile', 'CL'); 
insert into tb_pais (codigo, nome, sigla) values (44, 'China, Republica Popular', 'CN'); 
insert into tb_pais (codigo, nome, sigla) values (45, 'Christmas, Ilha (Navidad)', 'CX'); 
insert into tb_pais (codigo, nome, sigla) values (46, 'Cocos (Keeling), Ilhas', 'CC'); 
insert into tb_pais (codigo, nome, sigla) values (47, 'Colômbia', 'CO'); 
insert into tb_pais (codigo, nome, sigla) values (48, 'Comores, Ilhas', 'KM'); 
insert into tb_pais (codigo, nome, sigla) values (49, 'Congo', 'CG'); 
insert into tb_pais (codigo, nome, sigla) values (50, 'Congo, Republica Democrática do', 'CD'); 
insert into tb_pais (codigo, nome, sigla) values (51, 'Cook, Ilhas', 'CK'); 
insert into tb_pais (codigo, nome, sigla) values (52, 'Costa Rica', 'CR'); 
insert into tb_pais (codigo, nome, sigla) values (53, 'Costa do Marfim', 'CI'); 
insert into tb_pais (codigo, nome, sigla) values (54, 'Croácia (Republica da)', 'HR'); 
insert into tb_pais (codigo, nome, sigla) values (55, 'Cuba', 'CU'); 
insert into tb_pais (codigo, nome, sigla) values (56, 'Chipre', 'CY'); 
insert into tb_pais (codigo, nome, sigla) values (57, 'Tcheca, Republica', 'CZ'); 
insert into tb_pais (codigo, nome, sigla) values (58, 'Dinamarca', 'DK'); 
insert into tb_pais (codigo, nome, sigla) values (59, 'Djibuti', 'DJ'); 
insert into tb_pais (codigo, nome, sigla) values (60, 'Dominica, Ilha', 'DM'); 
insert into tb_pais (codigo, nome, sigla) values (61, 'Republica Dominicana', 'DO'); 
insert into tb_pais (codigo, nome, sigla) values (62, 'Timor Leste', 'TL'); 
insert into tb_pais (codigo, nome, sigla) values (63, 'Equador', 'EC'); 
insert into tb_pais (codigo, nome, sigla) values (64, 'Egito', 'EG'); 
insert into tb_pais (codigo, nome, sigla) values (65, 'El Salvador', 'SV'); 
insert into tb_pais (codigo, nome, sigla) values (66, 'Guine-Equatorial', 'GQ'); 
insert into tb_pais (codigo, nome, sigla) values (67, 'Eritreia', 'ER'); 
insert into tb_pais (codigo, nome, sigla) values (68, 'Estônia, Republica da', 'EE'); 
insert into tb_pais (codigo, nome, sigla) values (69, 'Etiópia', 'ET'); 
insert into tb_pais (codigo, nome, sigla) values (70, 'Falkland (Ilhas Malvinas)', 'FK'); 
insert into tb_pais (codigo, nome, sigla) values (71, 'Feroe, Ilhas', 'FO'); 
insert into tb_pais (codigo, nome, sigla) values (72, 'Fiji', 'FJ'); 
insert into tb_pais (codigo, nome, sigla) values (73, 'Finlândia', 'FI'); 
insert into tb_pais (codigo, nome, sigla) values (74, 'Franca', 'FR'); 
insert into tb_pais (codigo, nome, sigla) values (76, 'Guiana francesa', 'GF'); 
insert into tb_pais (codigo, nome, sigla) values (77, 'Polinésia Francesa', 'PF'); 
insert into tb_pais (codigo, nome, sigla) values (78, 'Terras Austrais e Antárticas Francesas', 'TF'); 
insert into tb_pais (codigo, nome, sigla) values (79, 'Gabão', 'GA'); 
insert into tb_pais (codigo, nome, sigla) values (80, 'Gambia', 'GM'); 
insert into tb_pais (codigo, nome, sigla) values (81, 'Georgia, Republica da', 'GE'); 
insert into tb_pais (codigo, nome, sigla) values (82, 'Alemanha', 'DE'); 
insert into tb_pais (codigo, nome, sigla) values (83, 'Gana', 'GH'); 
insert into tb_pais (codigo, nome, sigla) values (84, 'Gibraltar', 'GI'); 
insert into tb_pais (codigo, nome, sigla) values (85, 'Grécia', 'GR'); 
insert into tb_pais (codigo, nome, sigla) values (86, 'Groenlândia', 'GL'); 
insert into tb_pais (codigo, nome, sigla) values (87, 'Granada', 'GD'); 
insert into tb_pais (codigo, nome, sigla) values (88, 'Guadalupe', 'GP'); 
insert into tb_pais (codigo, nome, sigla) values (89, 'Guam', 'GU'); 
insert into tb_pais (codigo, nome, sigla) values (90, 'Guatemala', 'GT'); 
insert into tb_pais (codigo, nome, sigla) values (91, 'Guine', 'GN'); 
insert into tb_pais (codigo, nome, sigla) values (92, 'Guine-Bissau', 'GW'); 
insert into tb_pais (codigo, nome, sigla) values (93, 'Guiana', 'GY'); 
insert into tb_pais (codigo, nome, sigla) values (94, 'Haiti', 'HT'); 
insert into tb_pais (codigo, nome, sigla) values (95, 'Ilha Heard e Ilhas McDonald', 'HM'); 
insert into tb_pais (codigo, nome, sigla) values (96, 'Vaticano, Estado da Cidade do', 'VA'); 
insert into tb_pais (codigo, nome, sigla) values (97, 'Honduras', 'HN'); 
insert into tb_pais (codigo, nome, sigla) values (98, 'Hong Kong', 'HK'); 
insert into tb_pais (codigo, nome, sigla) values (99, 'Hungria, Republica da', 'HU'); 
insert into tb_pais (codigo, nome, sigla) values (100, 'Islândia', 'IS'); 
insert into tb_pais (codigo, nome, sigla) values (101, 'Índia', 'IN'); 
insert into tb_pais (codigo, nome, sigla) values (102, 'Indonésia', 'ID'); 
insert into tb_pais (codigo, nome, sigla) values (103, 'Ira, Republica Islâmica do', 'IR'); 
insert into tb_pais (codigo, nome, sigla) values (104, 'Iraque', 'IQ'); 
insert into tb_pais (codigo, nome, sigla) values (105, 'Irlanda', 'IE'); 
insert into tb_pais (codigo, nome, sigla) values (106, 'Israel', 'IL'); 
insert into tb_pais (codigo, nome, sigla) values (107, 'Itália', 'IT'); 
insert into tb_pais (codigo, nome, sigla) values (108, 'Jamaica', 'JM'); 
insert into tb_pais (codigo, nome, sigla) values (109, 'Japão', 'JP'); 
insert into tb_pais (codigo, nome, sigla) values (110, 'Jordânia', 'JO'); 
insert into tb_pais (codigo, nome, sigla) values (111, 'Cazaquistão, Republica do', 'KZ'); 
insert into tb_pais (codigo, nome, sigla) values (112, 'Quênia', 'KE'); 
insert into tb_pais (codigo, nome, sigla) values (113, 'Kiribati', 'KI'); 
insert into tb_pais (codigo, nome, sigla) values (114, 'Coreia, Republica Popular Democrática da', 'KP'); 
insert into tb_pais (codigo, nome, sigla) values (115, 'Coreia, Republica da', 'KR'); 
insert into tb_pais (codigo, nome, sigla) values (116, 'Kuwait', 'KW'); 
insert into tb_pais (codigo, nome, sigla) values (117, 'Quirguiz, Republica', 'KG'); 
insert into tb_pais (codigo, nome, sigla) values (118, 'Laos, Republica Popular Democrática do', 'LA'); 
insert into tb_pais (codigo, nome, sigla) values (119, 'Letônia, Republica da', 'LV'); 
insert into tb_pais (codigo, nome, sigla) values (120, 'Líbano', 'LB'); 
insert into tb_pais (codigo, nome, sigla) values (121, 'Lesoto', 'LS'); 
insert into tb_pais (codigo, nome, sigla) values (122, 'Libéria', 'LR'); 
insert into tb_pais (codigo, nome, sigla) values (123, 'Líbia', 'LY'); 
insert into tb_pais (codigo, nome, sigla) values (124, 'Liechtenstein', 'LI'); 
insert into tb_pais (codigo, nome, sigla) values (125, 'Lituânia, Republica da', 'LT'); 
insert into tb_pais (codigo, nome, sigla) values (126, 'Luxemburgo', 'LU'); 
insert into tb_pais (codigo, nome, sigla) values (127, 'Macau', 'MO'); 
insert into tb_pais (codigo, nome, sigla) values (128, 'Macedônia do Norte', 'MK'); 
insert into tb_pais (codigo, nome, sigla) values (129, 'Madagascar', 'MG'); 
insert into tb_pais (codigo, nome, sigla) values (130, 'Malavi', 'MW'); 
insert into tb_pais (codigo, nome, sigla) values (131, 'Malásia', 'MY'); 
insert into tb_pais (codigo, nome, sigla) values (132, 'Maldivas', 'MV'); 
insert into tb_pais (codigo, nome, sigla) values (133, 'Mali', 'ML'); 
insert into tb_pais (codigo, nome, sigla) values (134, 'Malta', 'MT'); 
insert into tb_pais (codigo, nome, sigla) values (135, 'Marshall, Ilhas', 'MH'); 
insert into tb_pais (codigo, nome, sigla) values (136, 'Martinica', 'MQ'); 
insert into tb_pais (codigo, nome, sigla) values (137, 'Mauritânia', 'MR'); 
insert into tb_pais (codigo, nome, sigla) values (138, 'Mauricio', 'MU'); 
insert into tb_pais (codigo, nome, sigla) values (139, 'Mayotte (Ilhas Francesas)', 'YT'); 
insert into tb_pais (codigo, nome, sigla) values (140, 'México', 'MX'); 
insert into tb_pais (codigo, nome, sigla) values (141, 'Micronesia', 'FM'); 
insert into tb_pais (codigo, nome, sigla) values (142, 'Moldávia, Republica da', 'MD'); 
insert into tb_pais (codigo, nome, sigla) values (143, 'Mônaco', 'MC'); 
insert into tb_pais (codigo, nome, sigla) values (144, 'Mongólia', 'MN'); 
insert into tb_pais (codigo, nome, sigla) values (145, 'Montserrat, Ilhas', 'MS'); 
insert into tb_pais (codigo, nome, sigla) values (146, 'Marrocos', 'MA'); 
insert into tb_pais (codigo, nome, sigla) values (147, 'Moçambique', 'MZ'); 
insert into tb_pais (codigo, nome, sigla) values (148, 'Mianmar (Birmânia)', 'MM'); 
insert into tb_pais (codigo, nome, sigla) values (149, 'Namíbia', 'NA'); 
insert into tb_pais (codigo, nome, sigla) values (150, 'Nauru', 'NR'); 
insert into tb_pais (codigo, nome, sigla) values (151, 'Nepal', 'NP'); 
insert into tb_pais (codigo, nome, sigla) values (152, 'Países Baixos (Holanda)', 'NL'); 
insert into tb_pais (codigo, nome, sigla) values (154, 'Nova Caledonia', 'NC'); 
insert into tb_pais (codigo, nome, sigla) values (155, 'Nova Zelândia', 'NZ'); 
insert into tb_pais (codigo, nome, sigla) values (156, 'Nicarágua', 'NI'); 
insert into tb_pais (codigo, nome, sigla) values (157, 'Níger', 'NE'); 
insert into tb_pais (codigo, nome, sigla) values (158, 'Nigéria', 'NG'); 
insert into tb_pais (codigo, nome, sigla) values (159, 'Niue, Ilha', 'NU'); 
insert into tb_pais (codigo, nome, sigla) values (160, 'Norfolk, Ilha', 'NF'); 
insert into tb_pais (codigo, nome, sigla) values (161, 'Marianas do Norte', 'MP'); 
insert into tb_pais (codigo, nome, sigla) values (162, 'Noruega', 'NO'); 
insert into tb_pais (codigo, nome, sigla) values (163, 'Oma', 'OM'); 
insert into tb_pais (codigo, nome, sigla) values (164, 'Paquistão', 'PK'); 
insert into tb_pais (codigo, nome, sigla) values (165, 'Palau', 'PW'); 
insert into tb_pais (codigo, nome, sigla) values (166, 'Panamá', 'PA'); 
insert into tb_pais (codigo, nome, sigla) values (167, 'Papua Nova Guine', 'PG'); 
insert into tb_pais (codigo, nome, sigla) values (168, 'Paraguai', 'PY'); 
insert into tb_pais (codigo, nome, sigla) values (169, 'Peru', 'PE'); 
insert into tb_pais (codigo, nome, sigla) values (170, 'Filipinas', 'PH'); 
insert into tb_pais (codigo, nome, sigla) values (171, 'Pitcairn, Ilha', 'PN'); 
insert into tb_pais (codigo, nome, sigla) values (172, 'Polônia, Republica da', 'PL'); 
insert into tb_pais (codigo, nome, sigla) values (173, 'Portugal', 'PT'); 
insert into tb_pais (codigo, nome, sigla) values (174, 'Porto Rico', 'PR'); 
insert into tb_pais (codigo, nome, sigla) values (175, 'Catar', 'QA'); 
insert into tb_pais (codigo, nome, sigla) values (176, 'Reunião, Ilha', 'RE'); 
insert into tb_pais (codigo, nome, sigla) values (177, 'Romênia', 'RO'); 
insert into tb_pais (codigo, nome, sigla) values (178, 'Rússia, Federação da', 'RU'); 
insert into tb_pais (codigo, nome, sigla) values (179, 'Ruanda', 'RW'); 
insert into tb_pais (codigo, nome, sigla) values (180, 'São Cristovão e Neves, Ilhas', 'KN'); 
insert into tb_pais (codigo, nome, sigla) values (181, 'Santa Lucia', 'LC'); 
insert into tb_pais (codigo, nome, sigla) values (182, 'São Vicente e Granadinas', 'VC'); 
insert into tb_pais (codigo, nome, sigla) values (183, 'Samoa', 'WS'); 
insert into tb_pais (codigo, nome, sigla) values (184, 'San Marino', 'SM'); 
insert into tb_pais (codigo, nome, sigla) values (185, 'São Tome e Príncipe, Ilhas', 'ST'); 
insert into tb_pais (codigo, nome, sigla) values (186, 'Arábia Saudita', 'SA'); 
insert into tb_pais (codigo, nome, sigla) values (187, 'Senegal', 'SN'); 
insert into tb_pais (codigo, nome, sigla) values (188, 'Seychelles', 'SC'); 
insert into tb_pais (codigo, nome, sigla) values (189, 'Serra Leoa', 'SL'); 
insert into tb_pais (codigo, nome, sigla) values (190, 'Cingapura', 'SG'); 
insert into tb_pais (codigo, nome, sigla) values (191, 'Eslovaca, Republica', 'SK'); 
insert into tb_pais (codigo, nome, sigla) values (192, 'Eslovênia, Republica da', 'SI'); 
insert into tb_pais (codigo, nome, sigla) values (193, 'Salomão, Ilhas', 'SB'); 
insert into tb_pais (codigo, nome, sigla) values (194, 'Somalia', 'SO'); 
insert into tb_pais (codigo, nome, sigla) values (195, 'África do Sul', 'ZA'); 
insert into tb_pais (codigo, nome, sigla) values (196, 'Ilhas Geórgia do Sul e Sandwich do Sul', 'GS'); 
insert into tb_pais (codigo, nome, sigla) values (197, 'Espanha', 'ES'); 
insert into tb_pais (codigo, nome, sigla) values (198, 'Sri Lanka', 'LK'); 
insert into tb_pais (codigo, nome, sigla) values (199, 'Santa Helena', 'SH'); 
insert into tb_pais (codigo, nome, sigla) values (200, 'São Pedro e Miquelon', 'PM'); 
insert into tb_pais (codigo, nome, sigla) values (201, 'Sudão', 'SD'); 
insert into tb_pais (codigo, nome, sigla) values (202, 'Suriname', 'SR');